#config file version
apiVersion: 1

# list of datasoruces to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: ml_metrics_db
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'